# debug using `werft run github -f -s .werft/build.js -j .werft/build.yaml -a debug=true`
pod:
  serviceAccount: werft
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dev/workload
            operator: In
            values:
            - "builds"
  volumes:
  - name: gcp-sa
    secret:
      secretName: gcp-sa-gitpod-dev-deployer
  - name: gcp-sa-release
    secret:
      secretName: gcp-sa-gitpod-release-deployer
  containers:
  - name: build
    image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:prs-ws-man-bridge-audit.10
    workingDir: /workspace
    imagePullPolicy: Always
    volumeMounts:
    - name: gcp-sa
      mountPath: /mnt/secrets/gcp-sa
      readOnly: true
    - name: gcp-sa-release
      mountPath: /mnt/secrets/gcp-sa-release
      readOnly: true
    env:
    - name: WERFT_HOST
      value: "werft.werft.svc.cluster.local:7777"
    - name: NODENAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: HONEYCOMB_DATASET
      value: "werft"
    - name: HONEYCOMB_API_KEY
      valueFrom:
        secretKeyRef:
          name: honeycomb-api-key
          key: apikey
    command:
      - bash
      - -c
      - |
        sleep 1
        set -Eeuo pipefail

        export DOCKER_HOST=tcp://$NODENAME:2375
        sudo chown -R gitpod:gitpod /workspace

        (cd .werft && yarn install && mv node_modules ..) | werft log slice prep
        printf '{{ toJson . }}' > context.json

        npx ts-node .werft/delete-preview-environments/delete-preview-environments.ts
sidecars:
- testdb
