# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

---
- name: Install dependencies
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    update_cache: yes
    state: present
  become: true

- name: Install docker Python library
  pip:
    name:
      - docker
    state: present
  become: true

- name: Add Docker Apt signing key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: present
  become: true

- name: Start registry container
  community.docker.docker_container:
    name: registry
    image: registry:2
    volumes:
      - /var/lib/registry
      # - ./cert:/certs
    ports:
      - "5000:5000"
    # env:
    #   REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
    #   REGISTRY_HTTP_TLS_KEY: /cert/privkey.pem
    state: started
